[colors.bright]
black = "{color0}"
blue = "{color4}"
cyan = "{color6}"
green = "{color2}"
magenta = "{color5}"
red = "{color1}"
white = "{color7}"
yellow = "{color3}"

[colors.cursor]
cursor = "{cursor}"
text = "CellForeground"

[colors.normal]
black = "{color8}"
blue = "{color12}"
cyan = "{color14}"
green = "{color10}"
magenta = "{color13}"
red = "{color9}"
white = "{color15}"
yellow = "{color11}"

[colors.primary]
background = "{background}"
foreground = "{foreground}"

[window]
opacity = 100
